### ISSUE TITLE
Minecraft crashing on loading of falling blocks

### ISSUE THREAD

**Issue by MinerBruh** [Redi2Go/PhotonicEngine#64]
Pretty self explanatory from my understanding the game crashes when it tries to render a falling block. Here's the log if you wanna take a closer look

```
at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.<init>(CtmBakedModel.java:86)
at java.base/java.lang.ThreadLocal.get(Unknown Source)
at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source)
at java.base/java.lang.ThreadLocal.setInitialValue(Unknown Source)
at java.base/java.lang.ThreadLocal.get(Unknown Source)
at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
at net.minecraft.class_901.method_3965(class_901.java:45)
at net.minecraft.class_901.method_3936(class_901.java:17)
at net.minecraft.class_898.method_3954(class_898.java:148)
at net.minecraft.class_761.method_22977(class_761.java:1312)
at net.minecraft.class_761.invokeRenderEntity(class_761.java)
at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:636)
at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:505)
at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1020)
at net.minecraft.class_761.handler$bfg000$iris$renderTerrainShadows(class_761.java:6277)
at net.minecraft.class_761.method_22710(class_761.java:977)
at net.minecraft.class_757.method_3188(class_757.java:1087)
Details:
Entity Type: minecraft:falling_block (net.minecraft.class_1540)
Entity ID: 501
at net.minecraft.class_310.method_1514(class_310.java:902)
Space in storage for jna.tmpdir (MiB): available: 291716.38, total: 952983.00
net_neoforged_bus: bus 7.2.0
elementa: Elementa 665
fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
lithium: Lithium 0.13.1
modmenu: Mod Menu 11.0.2
nochatreports: No Chat Reports 1.21-v2.8.0
notenoughanimations: NotEnoughAnimations 1.7.6
org_jetbrains_annotations: annotations 23.0.0
photonics: Photonic 0.2.4
placeholder-api: Placeholder API 2.4.1+1.21
kirin: Kirin UI 1.19.0+1.21
skinlayers3d: 3d-Skin-Layers 1.6.7
sodium: Sodium 0.5.11+mc1.21
u_framework: Unnamed Framework 1.0.2
universalcraft: UniversalCraft 362
vigilance: Vigilance 306
Loaded Shaderpack: BSL_v8.2.09.zip
Profile: HIGH (+0 options changed by user)
Launched Version: 1.21.1
Launcher name: theseus
Backend library: LWJGL version 3.3.3-snapshot
Backend API: NVIDIA GeForce RTX 4060/PCIe/SSE2 GL version 3.2.0 NVIDIA 565.90, NVIDIA Corporation
Window size: 1920x1080
GFLW Platform: win32
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages:
Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
Universe: 400921fb54442d18
Type: Integrated Server (map_client.txt)
Graphics mode: fancy
Render Distance: 10/10 chunks
Resource Packs: vanilla, fabric, ambientsounds, cloth-config, continuity, creativecore, entity_model_features, entity_texture_features, essential (incompatible), essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fullscreenfix, immediatelyfast, iris, lithium, minecraftcapes (incompatible), modmenu, nochatreports, notenoughanimations, photonics, placeholder-api, presencefootsteps, skinlayers3d, sodium, u_framework (incompatible)
Current Language: en_us
Locale: en_US
System encoding: Cp1252
File encoding: UTF-8
CPU: 12x AMD Ryzen 5 4600G with Radeon Graphics
Server Running: true
Player Count: 1 / 8; [class_3222['{MINECRAFT_USERNAME}'/298, l='ServerLevel[New World]', x=-6.64, y=65.24, z=-3.51]]
Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, u_framework
Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, u_framework, vanilla
Enabled Feature Flags: minecraft:vanilla
World Generation: Stable
World Seed: -3083688530701765647
```

**Comment by MinerBruh** [comment]
After actually using my eyes, I realised that the mod causing the crash is continuity. So I removed it, and now my game isn't crashing
