### ISSUE TITLE
Stuck on loading Screen

### ISSUE THREAD

**Issue by Xenonidium** [Redi2Go/PhotonicEngine#68]
I use MacOS and playing on PrismLauncher with the latest version of photonics. Here is the mod list:
- Fabric API [0.107.0+1.21.1]
- Iris [1.7.3+mc1.21]
- Mod Menu [11.0.3]
- Photonic [0.2.4]
- Placeholder API [2.4.1+1.21]
- Sodium [0.5.11+mc1.21]

Issue is that while loading minecraft im stuch on the loading screen, progress bar loads twice thru and gets stuck. I can interact with the UI, but i cant see what elements im interacting with.

**Comment by RonaldIp** [comment]
Same issue here, resizing the window results in a black screen.

**Comment by adumeige** [comment]
Same issue on my mac m1.
Tested on a fresh Fabulously Optimised modpack from prism.
The exact same configuration works perfectly fine on my gaming PC (windows 10 + 3060ti with somewhat up to date drivers).

**Comment by Redi2Go** [comment]
I don't have access to a Mac computer, so unfortunately I cannot help you troubleshoot this problem.
Are there any errors in the logs?

**Comment by adumeige** [comment]
https://mclo.gs/3sKN6u7

I see a couple shader related lines, but I'm way out of my depth to say whether it's relevant or not.

**Comment by Redi2Go** [comment]
Seems like MacOS doesn't support OpenGL 4.3 with M1 chips.(4.3 was released in 2012). You might have better luck with linux (https://rosenzweig.io/blog/conformant-gl46-on-the-m1.html)

**Comment by Xenonidium** [comment]
> Seems like MacOS doesn't support OpenGL 4.3 with M1 chips.(4.3 was released in 2012). You might have better luck with linux (https://rosenzweig.io/blog/conformant-gl46-on-the-m1.html)

Hey Redi2Go, I use a macbook pro with the latest m3 chip, specifically an m3 pro with a 12 core cpu and an 18 core gpu. I'm not sure whether MacOS right now supports OpenGL 4.3, as I can't find the exact place to check it. Still looking, just wanted to update you on that.

**Comment by Xenonidium** [comment]
[17:32:13] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17:32:13] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: net.irisshaders.iris.helpers.FakeChainedJsonException: Invalid shaders/core/schematic6.json: 
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.8.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: net.irisshaders.iris.helpers.FakeChainedJsonException: Invalid shaders/core/schematic6.json: 
	at knot/net.minecraft.class_757.handler$bfb000$photonics$loadShaders(class_757.java:4638) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_34538(class_757.java:547) [client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
Caused by: net.irisshaders.iris.helpers.FakeChainedJsonException: Invalid shaders/core/schematic6.json: 
	at knot/net.minecraft.class_2973.handler$zni000$iris$changeShaderParseException(class_2973.java:516) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2973.method_12856(class_2973.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.<init>(class_5944.java:172) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.handler$bfb000$photonics$loadShaders(class_757.java:4632) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_34538(class_757.java:547) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
Caused by: net.irisshaders.iris.gl.shader.ShaderCompileException: schematic.fsh: schematic.fsh: ERROR: 0:1: '' :  version '430' is not supported
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:3: 'world_array_block' : syntax error: syntax error

	at knot/net.minecraft.class_281.handler$zpa000$iris$causeException(class_281.java:536) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_281.method_34416(class_281.java:68) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.method_34579(class_5944.java:210) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.<init>(class_5944.java:158) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.handler$bfb000$photonics$loadShaders(class_757.java:4632) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_34538(class_757.java:547) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more

Here is the error logs from my game, if that helps in resolving the problem. I didn't realise that it could be that MacOS itself is the bottleneck here with only having updated to OpenGL 4.1, and not 4.3

**Comment by Redi2Go** [comment]
Fortnunately, there is an error message telling you that OpenGL 4.3 is not supported: "ERROR: 0:1: '' : version '430' is not supported"

From the research I have done it seems like Apple has no intention on adding OpenGL 4.3 support and also has pronounced OpenGL deprecated for their platform. You may have some luck with Mesa Drivers on Linux, though
