### ISSUE TITLE
Game crashing when opening video settings

### ISSUE THREAD

**Issue by Mitzingdash** [Redi2Go/PhotonicEngine#69]
Whenever i open video settings the game crash. i tried disabling rees sodium options and sodium extra and individually and none of it worked. but whenever i disabled Photonics the crashing stopped. 

`[13:23:17] [Render thread/INFO]: Changing view distance to 8 (play stage)
[13:23:18] [Render thread/INFO]: Changing view distance to 8 (play stage)
[13:23:20] [Render thread/INFO]: Changing view distance to 8 (play stage)
[13:23:21] [Render thread/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[13:23:21] [Render thread/WARN]: Error loading class: net/caffeinemc/mods/sodium/client/gui/SodiumGameOptionPages (java.lang.ClassNotFoundException: net/caffeinemc/mods/sodium/client/gui/SodiumGameOptionPages)
[13:23:21] [Render thread/WARN]: @ModifyConstant conflict. Skipping photonics.mixins.json:SodiumGameOptionPagesMixin from mod photonics->@ModifyConstant::initViewDistanceSliderMaxValue0(I)I with priority 1000, already redirected by c2me-client-uncapvd.mixins.json:MixinSodiumUserConfigCategories from mod c2me-client-uncapvd->@ModifyConstant::modifyMaxViewDistance(I)I with priority 1100
[13:23:21] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at knot/net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
	at knot/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at knot/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1041.method_15998(class_1041.java:303) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1307) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.8.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:63) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:128) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/net.minecraft.class_429.handler$ddb000$sodium$open(class_429.java:522) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_19828(class_429.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_47624(class_429.java:171) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:63) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:128) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/net.minecraft.class_429.handler$ddb000$sodium$open(class_429.java:522) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_19828(class_429.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_47624(class_429.java:171) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method initViewDistanceSliderMaxValue0(I)I in photonics.mixins.json:SodiumGameOptionPagesMixin from mod photonics failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap Photonic-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:63) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:128) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/net.minecraft.class_429.handler$ddb000$sodium$open(class_429.java:522) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_19828(class_429.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_47624(class_429.java:171) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 19 more
[13:23:22] [Server thread/INFO]: Stopping server`

**Comment by CoderModeGit** [comment]
> [Render thread/WARN]: @ModifyConstant conflict. Skipping photonics.mixins.json:SodiumGameOptionPagesMixin from mod photonics-

Also getting this issue. This looks interesting.

**Comment by gegentan** [comment]
It also crashes (when opening video settings) with the bobby mod.

**Comment by 533kr** [comment]
Slightly different error phrasing, same overall issue--I hit the "video settings button" and boom, instant crash. I'm on the current/most recent Sodium version (0.5.11) and I've removed all the extra Sodium-related add-ons, but the only thing that stops the crashing is removing Photonic entirely. I'm on Fabric 1.20.1, crashlog attached:
- [crash-2024-11-12_22.41.07-client.txt](https://github.com/user-attachments/files/17725836/crash-2024-11-12_22.41.07-client.txt)

**Comment by Mitzingdash** [comment]
> Slightly different error phrasing, same overall issue--I hit the "video settings button" and boom, instant crash. I'm on the current/most recent Sodium version (0.5.11) and I've removed all the extra Sodium-related add-ons, but the only thing that stops the crashing is removing Photonic entirely. I'm on Fabric 1.20.1, crashlog attached:
> 
> - [crash-2024-11-12_22.41.07-client.txt](https://github.com/user-attachments/files/17725836/crash-2024-11-12_22.41.07-client.txt)
> 
> 

for me it fixed when i went from 1.21.1 down to 1.20.1
then it all worked. 
idk why its crashing for you at 1.20.1

**Comment by Poopooracoocoo** [comment]
Photonics seems to conflict with c2me

> `@ModifyConstant conflict. Skipping photonics.mixins.json:SodiumGameOptionPagesMixin from mod photonics->@ModifyConstant::initViewDistanceSliderMaxValue0(I)I with priority 1000, already redirected by c2me-client-uncapvd.mixins.json:MixinSodiumUserConfigCategories from mod c2me-client-uncapvd->@ModifyConstant::modifyMaxViewDistance(I)I with priority 1100`

**Comment by bghyt** [comment]
> Photonics seems to conflict with c2me
> 
> > `@ModifyConstant conflict. Skipping photonics.mixins.json:SodiumGameOptionPagesMixin from mod photonics->@ModifyConstant::initViewDistanceSliderMaxValue0(I)I with priority 1000, already redirected by c2me-client-uncapvd.mixins.json:MixinSodiumUserConfigCategories from mod c2me-client-uncapvd->@ModifyConstant::modifyMaxViewDistance(I)I with priority 1100`

I have the same issue but never had Bobby & C2ME installed.

**Comment by Mitzingdash** [comment]
> > Photonics seems to conflict with c2me
> 
> > 
> 
> > > `@ModifyConstant conflict. Skipping photonics.mixins.json:SodiumGameOptionPagesMixin from mod photonics->@ModifyConstant::initViewDistanceSliderMaxValue0(I)I with priority 1000, already redirected by c2me-client-uncapvd.mixins.json:MixinSodiumUserConfigCategories from mod c2me-client-uncapvd->@ModifyConstant::modifyMaxViewDistance(I)I with priority 1100`
> 
> 
> 
> I have the same issue but never had Bobby & C2ME installed.

for me it just got fixed when i downgraded from minecraft 1.21.1 down to 1.20.1

**Comment by Redi2Go** [comment]
The newest [release ](https://modrinth.com/mod/photonics/version/o9YBSd8A) fixes this bug
