### ISSUE TITLE
game crash when trying to go in video settings | mod version: 0.2.5 | game version 1.20.1 | fabric version 0.16.9-1

### ISSUE THREAD

**Issue by CrispyPanda01** [Redi2Go/PhotonicEngine#88]
![2024-11-08 23_13_36-Minecraft Launcher](https://github.com/user-attachments/assets/d0abb644-dcba-4b3b-a008-69aa5a261cb9)

crash log: 
Time: 2024-11-08 23:03:57
Description: mouseClicked event handler

java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:64)
	at knot//me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:129)
	at knot//net.minecraft.class_429.handler$bmi000$sodium$open(class_429.java:522)
	at knot//net.minecraft.class_429.method_19828(class_429.java)
	at knot//net.minecraft.class_429.method_47624(class_429.java:153)
	at knot//net.minecraft.class_4185.method_25306(class_4185.java:94)
	at knot//net.minecraft.class_4264.method_25348(class_4264.java:56)
	at knot//net.minecraft.class_339.method_25402(class_339.java:189)
	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
	at knot//net.minecraft.class_312.method_1611(class_312.java:98)
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)
	at knot//net.minecraft.class_312.method_1601(class_312.java:98)
	at knot//net.minecraft.class_312.method_22686(class_312.java:169)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_312.method_22684(class_312.java:169)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:288)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1241)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 31 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method initViewDistanceSliderMaxValue0(I)I in photonics.mixins.json:SodiumGameOptionPagesMixin from mod photonics failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap Photonic-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 34 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:64)
	at knot//me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:129)
	at knot//net.minecraft.class_429.handler$bmi000$sodium$open(class_429.java:522)
	at knot//net.minecraft.class_429.method_19828(class_429.java)
	at knot//net.minecraft.class_429.method_47624(class_429.java:153)
	at knot//net.minecraft.class_4185.method_25306(class_4185.java:94)
	at knot//net.minecraft.class_4264.method_25348(class_4264.java:56)
	at knot//net.minecraft.class_339.method_25402(class_339.java:189)
	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
	at knot//net.minecraft.class_312.method_1611(class_312.java:98)
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)
	at knot//net.minecraft.class_312.method_1601(class_312.java:98)
	at knot//net.minecraft.class_312.method_22686(class_312.java:169)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_312.method_22684(class_312.java:169)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)
	at knot//net.minecraft.class_312.method_1601(class_312.java:98)
	at knot//net.minecraft.class_312.method_22686(class_312.java:169)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_312.method_22684(class_312.java:169)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:288)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1241)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['mymcname'/19, l='ClientLevel', x=-191.16, y=-42.00, z=-171.28]]
	Chunk stats: 4096, 899
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-42,0), Section: (at 0,6,0 in 0,-3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 102925 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at knot//net.minecraft.class_638.method_8538(class_638.java:458)
	at knot//net.minecraft.class_310.method_1587(class_310.java:2406)
	at knot//net.minecraft.class_310.method_1514(class_310.java:821)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

	Fabric Mods: 
		boostedbrightness: Boosted Brightness 2.2.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.5
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.5
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.5
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.5
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.5
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.5
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.5
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.5
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.5
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.5
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.5
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.5
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.5
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.5
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.5
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.5
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		indium: Indium 1.0.34+mc1.20.1
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		litematica: Litematica 0.15.3
		malilib: MaLiLib 0.16.3
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		noisium: Noisium 2.0.3+mc1.20-1.20.1
		photonics: Photonic 0.2.5
		sodium: Sodium 0.5.11+mc1.20.1
	Loaded Shaderpack: BSLOriginal_v8.3.zip
		Profile: HIGH (+0 options changed by user)
	Launched Version: fabric-loader-0.16.9-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT

**Comment by bghyt** [comment]
How did you fix this issue? nothing i do seems to solve it at all.

**Comment by Redi2Go** [comment]
c2me is incompatible with Photonics
